# Generated by Django 3.1.2 on 2021-04-19 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis', '0001_initial'),
        ('transcript', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=9)),
                ('name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('curriculum', smart_selects.db_fields.ChainedForeignKey(chained_field='program', chained_model_field='program', on_delete=django.db.models.deletion.CASCADE, to='sis.curriculum')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.faculty')),
                ('program', smart_selects.db_fields.ChainedForeignKey(chained_field='faculty', chained_model_field='faculty', on_delete=django.db.models.deletion.CASCADE, to='sis.program')),
                ('transcript', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcript.transcript')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
