# Generated by Django 3.1.2 on 2021-04-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('AA', 'Aa'), ('BA', 'Ba'), ('BB', 'Bb'), ('CB', 'Cb'), ('CC', 'Cc'), ('DC', 'Dc'), ('DD', 'Dd'), ('FF', 'Ff'), ('VF', 'Vf')], default='AA', max_length=2)),
                ('failed_before', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.course')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('courses', models.ManyToManyField(to='transcript.CourseT')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.ManyToManyField(to='transcript.Term')),
            ],
        ),
    ]
